# Generated by Django 4.0.1 on 2022-01-21 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Eventname', models.CharField(max_length=100, unique=True)),
                ('Desc', models.TextField()),
                ('inputAddress', models.TextField()),
                ('inputCity', models.CharField(max_length=100)),
                ('inputState', models.CharField(max_length=100)),
                ('inputZip', models.CharField(max_length=100)),
                ('Eventstart', models.DateField()),
                ('Eventstartt', models.TimeField()),
                ('Eventend', models.DateField()),
                ('Eventendt', models.TimeField()),
                ('Eventreg', models.DateField()),
                ('Eventregt', models.TimeField()),
                ('inputEmail4', models.EmailField(max_length=254)),
                ('inputPassword4', models.CharField(max_length=10)),
            ],
        ),
    ]
