# Generated by Django 4.0.1 on 2022-01-25 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0004_alter_participant_inlineradio2_alter_participant_pno'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='eventID',
            field=models.CharField(default='None', max_length=100),
            preserve_default=False,
        ),
    ]
