# Generated by Django 4.0.1 on 2022-01-27 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0006_alter_participant_contact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='inlineRadio2',
        ),
    ]
