# Generated by Django 4.0.1 on 2022-01-21 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('Email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=100, unique=True)),
                ('inlineRadio1', models.BooleanField()),
                ('inlineRadio2', models.BooleanField()),
                ('pno', models.PositiveIntegerField()),
            ],
        ),
    ]
